config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :restaurants do
    resources :dishes
    resources :ingredients
  end

  resources :ingredients, only: [] do
    get :decrease_stock_quantity
  end

  resources :dishes do
    resources :dish_ingredients
  end

  resources :dish_ingredients, only: [:update]

  resources :orders, only: :show do
    get :checkout
  end

  resources :order_items, only: [:show, :create, :destroy] do
    resources :special_requests, only: [:create, :destroy]
  end

  resources :special_requests, only: [] do
    patch :decrease_amount
    patch :increase_amount
  end

  resources :customized_ingredients, only: [] do
    patch :decrease_amount
    patch :increase_amount
  end

  get "/my_restaurants", to: 'dashboard#my_restaurants'
  get "/edit_stock", to: 'dashboard#edit_stock', as: 'edit_stock'
  post '/update_stock', to: 'dashboard#update_stock', as: 'update_stock'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def my_restaurants
    @user = current_user
    @restaurants = @user.restaurants
  end

  def edit_stock
    @user = current_user
    @restaurants = @user.restaurants
  end
  
  def update_stock
    result = Ingredient.update(params[:ingredients].keys, params[:ingredients].values).reject { |p| p.errors.empty? }
    if result.empty?
      flash[:notice] = "Ingredients updated"
      redirect_to edit_stock_path(page: params[:page])
    else
      ingredient_ids = result.collect {|i| i.id}
      flash[:error] = "Error(s) occurred updating ingredients(s): #{ingredient_ids.join ', '}"
      redirect_to edit_stock_path(page: params[:page])
    end
  end
end

app/views/dashboard/edit_stock.html.erb
<section>

<%= form_tag update_stock_path :method => :post do %>
  <%= hidden_field_tag 'page', (params[:page].nil? ? 1 : params[:page]) %>
  <table class='table table-striped table-condensed'>
    <thead>
      <tr>
        <th>Restaurant</th>
        <th>Ingredient Name</th>
        <th>Unit of Measure</th>
        <th>Change Increment</th>
        <th>Cost</th>
        <th>Price</th>
        <th>Stock Quantity</th>

      </tr>
    </thead>
    <tbody>
      <% @restaurants.each do |restaurant| %>


        <% restaurant.ingredients.each do |ingredient| %>
          <%= fields_for "ingredients[]", ingredient do |f| %>
            <tr>
              <td>
                <%= restaurant.name %>

              <td>
                <%= f.text_field :name %>
              </td>
              <td>
                <%= f.text_field :unit %>
              </td>
                <td>
                <%= f.text_field :change_increment %>
              </td>

              <td>
                <%= f.text_field :cost %>
              </td>
                <td>
                <%= f.text_field :price %>
              </td>
              <td>
                <%= f.text_field :stock_quantity %>
              </td>

            </tr>
          <% end %>
        <% end %>
        <% end %>
    </tbody>
  </table>
  <p><%= submit_tag "Update Ingredients", :class => 'btn btn-success' %></p>
<% end %>

</section>

app/views/dashboard/my_restaurants.html.erb
<section>

  <div class="main-container d-flex justify-content-between">
    <div class="restaurants-wrapper">
      <div class="d-flex justify-content-end" >
        <%= link_to "Add Restaurant", new_restaurant_path, class: "btn orange-button" %>
      </div>
      <div class="row">
        <% @restaurants.each do |restaurant| %>
          <div class="col-12 col-md-6 col-sm-12 col-lg-4">
            <div class="card-trip">
              <% if restaurant.photo.attached? %>
                <%= cl_image_tag restaurant.photo.key, height: 300, crop: :fill, class: "card-trip-image" %>
              <% else %>
                <%= image_tag 'https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80', class: "card-trip-image" %>
              <% end %>
              <div class="card-trip-infos">
                <div>
                  <%= link_to restaurant_path(restaurant) do %>
                    <h2 style="color: white !important"><%= restaurant.name %></h2>
                  <% end %>
                  <p><%= restaurant.cuisine %></p>
                </div>
                <p class="card-trip-pricing"><i class="fas fa-map-marker-alt mr-1"></i><%= restaurant.show_distance%> km</p>
                <span class="card-trip-user rating-stars">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star-half-alt"></i>
                </span>
              </div>
            </div>
            <div class="d-flex justify-content-end">
              <%= link_to 'Delete', restaurant_path(restaurant), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-secondary ml-1" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

</section>