config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :restaurants do
    resources :dishes
    resources :ingredients
  end

  resources :ingredients, only: [] do
    get :decrease_stock_quantity
  end

  resources :dishes do
    resources :dish_ingredients
  end

  resources :dish_ingredients, only: [:update]

  resources :orders, only: :show do
    get :checkout
  end

  resources :order_items, only: [:show, :create, :destroy] do
    resources :special_requests, only: [:create, :destroy]
  end

  resources :special_requests, only: [] do
    patch :decrease_amount
    patch :increase_amount
  end

  resources :customized_ingredients, only: [] do
    patch :decrease_amount
    patch :increase_amount
  end

  get "/my_restaurants", to: 'dashboard#my_restaurants'
  get "/edit_stock", to: 'dashboard#edit_stock', as: 'edit_stock'
  post '/update_stock', to: 'dashboard#update_stock', as: 'update_stock'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= yield(:navbar_class) %>">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "horizontal.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "All Restaurants", restaurants_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

            <% if current_user.orders.last.present? %>
              <%= link_to "My Basket", order_path(current_user.orders.last), class: "dropdown-item" %>
            <% end %>

            <% if !current_user.restaurants.empty? %>
            <%= link_to "My Restaurants", my_restaurants_path, class: "dropdown-item" %>
            <%= link_to "Ingredient Stock", edit_stock_path, class: "dropdown-item" %>
            <% end %>

            <%= link_to "Add New Restaurant", new_restaurant_path, class: "dropdown-item" %>

            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>

          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>