config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :restaurants do
    resources :dishes
    resources :ingredients
  end

  resources :ingredients, only: [] do
    get :decrease_stock_quantity
  end

  resources :dishes do
    resources :dish_ingredients
  end

  resources :dish_ingredients, only: [:update]

  resources :orders, only: :show do
    get :checkout
  end

  resources :order_items, only: [:show, :create, :destroy] do
    resources :special_requests, only: [:create, :destroy]
  end

  resources :special_requests, only: [] do
    patch :decrease_amount
    patch :increase_amount
  end

  resources :customized_ingredients, only: [] do
    patch :decrease_amount
    patch :increase_amount
  end

  get "/my_restaurants", to: 'dashboard#my_restaurants'
  get "/edit_stock", to: 'dashboard#edit_stock', as: 'edit_stock'
  post '/update_stock', to: 'dashboard#update_stock', as: 'update_stock'

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :restaurant
  has_many :dish_ingredients, dependent: :destroy
  has_many :special_requests, dependent: :destroy

  validates_presence_of :name, :unit, :change_increment, :cost, :price, :stock_quantity
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @ingredients = @restaurant.ingredients
  end

  def new
    @ingredient = Ingredient.new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @ingredient.restaurant = @restaurant
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @ingredient.restaurant = @restaurant

    if @ingredient.save
      redirect_to restaurant_ingredients_path
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:restaurant_id])

    @ingredient.restaurant = @restaurant

    unless @restaurant.user == current_user
      redirect_to @restaurant
    end
  end

  def update
    @ingredient.update(ingredient_params)
    redirect_to restaurant_ingredients_path(@ingredient.restaurant,  anchor: "id-#{@ingredient.id}")
  end

  def destroy
    @ingredient.destroy
    redirect_to restaurant_ingredients_path
  end

  def decrease_stock_quantity
    @order = Order.find(params[:ingredient_id])
    @order.order_items.each do |order_item|
      order_item.customized_ingredients.each do |customized_ingredient|
        customized_ingredient.dish_ingredient.ingredient.stock_quantity -= customized_ingredient.quantity
        customized_ingredient.dish_ingredient.ingredient.save!
      end
      order_item.special_requests.each do |special_request|
        special_request.ingredient.stock_quantity -= special_request.quantity
        special_request.ingredient.save!
      end
    end
    redirect_to order_checkout_path(@order)
  end

  private

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def ingredient_params
    params.require(:ingredient).permit(
      :name, :unit, :change_increment, :cost, :price, :stock_quantity
    )
  end
end

app/views/ingredients/edit.html.erb
<section>

<div class="container">
  <div class="special-row justify-content-center">
    <div class="h-100 col-xs-12 col-sm-10 col-sm-offset-1 mt-3">
      <h1>Update ingredient</h1>
      <%= simple_form_for  [@restaurant, @ingredient]  do |f| %>
          <%= f.input :name %>
          <%= f.input :unit %>
          <%= f.input :change_increment %>
          <%= f.input :cost %>
          <%= f.input :price %>
          <%= f.input :stock_quantity %>

          <%= f.submit class: 'btn btn-primary'%>
      <% end %>
    </div>
  </div>
  <%= link_to "Back to all ingredients", restaurant_ingredients_path(@restaurant), class: "btn btn-primary" %>
</div>

</section>

app/views/ingredients/index.html.erb
<section>

  <div class="container my-3">
    <div class="d-flex justify-content-end mb-2">
      <%= link_to 'Add Ingredient', new_restaurant_ingredient_path(@restaurant), class: "btn orange-button" %>
    </div>

    <div class="row">
      <% @ingredients.each do |ingredient| %>
        <div class="col-12 col-md-6 col-sm-12 col-lg-3 my-2">
          <div class="card rounded h-100 d-flex d-column">
            <div class="d-flex justify-content-between p-3">
              <div id="<%= ingredient.id %>" >
                <p class="text-bold">Ingredient name: <%= ingredient.name %></p>
                <p class="text-bold">Unit: <%= ingredient.unit %></p>
                <p class="text-bold">Increment: <%= ingredient.change_increment %></p>
                <p class="text-bold">Cost: <%= ingredient.cost %></p>
                <p class="text-bold">Price: <%= ingredient.price %></p>
                <p class="text-bold">Stock: <%= ingredient.stock_quantity %></p>
              </div>
            </div>
            <div class="card-footer text-muted mt-auto">
              <%= link_to 'Edit', edit_restaurant_ingredient_path(@restaurant, ingredient), class: "btn btn-secondary" %>
              <%= link_to 'Delete', restaurant_ingredient_path(@restaurant, ingredient), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-secondary ml-1" %>
            </div>
          </div>
        </div>
      <% end %>
      </div>
      <%= link_to "Back to #{@restaurant.name} Restaurant", restaurant_path(@restaurant), class: "btn purple-button mt-2" %>
    </div>
  </div>

</section>

app/views/ingredients/new.html.erb
<section>

  <div class="container my-3">
    <div class="special-row justify-content-center">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1 mt-3">
        <h1>Create a new ingredient for
          <%= @restaurant.name %> Restaurant
        </h1>

        <%= simple_form_for  [@restaurant, @ingredient]  do |f| %>
          <%= f.input :name %>
          <%= f.input :unit %>
          <%= f.input :change_increment %>
          <%= f.input :cost %>
          <%= f.input :price %>
          <%= f.input :stock_quantity %>
          <%= f.submit class: 'btn btn-primary'%>
        <% end %>
      </div>
    </div>
      <%= link_to "Back to all ingredients", restaurant_ingredients_path(@restaurant), class: "btn purple-button" %>
  </div>

</section>