config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :restaurants do
    resources :dishes
    resources :ingredients
  end

  resources :ingredients, only: [] do
    get :decrease_stock_quantity
  end

  resources :dishes do
    resources :dish_ingredients
  end

  resources :dish_ingredients, only: [:update]

  resources :orders, only: :show do
    get :checkout
  end

  resources :order_items, only: [:show, :create, :destroy] do
    resources :special_requests, only: [:create, :destroy]
  end

  resources :special_requests, only: [] do
    patch :decrease_amount
    patch :increase_amount
  end

  resources :customized_ingredients, only: [] do
    patch :decrease_amount
    patch :increase_amount
  end

  get "/my_restaurants", to: 'dashboard#my_restaurants'
  get "/edit_stock", to: 'dashboard#edit_stock', as: 'edit_stock'
  post '/update_stock', to: 'dashboard#update_stock', as: 'update_stock'

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CUISINES = ["Lebanese", "Indian", "Italian", "Thai", "Chinese", "French", "Azerbaijani", "Moroccan", "International", "Brasilian", "British", "Russian", "Asian", "Spanish", "Portoguese", "Japanese", "Mexican", "Arabic"]
  belongs_to :user
  has_many :dishes, dependent: :destroy
  has_many :ingredients, dependent: :destroy

  validates_presence_of :name, :address, :phone_number, :cuisine
  validates :name, uniqueness: true
  validates :cuisine, inclusion: { in: CUISINES }
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def show_distance
    distance([25.102980004648156, 55.16300169747915], [self.latitude, self.longitude])
  end

  def distance(loc1, loc2)
    rad_per_deg = Math::PI / 180  # PI / 180
    rkm = 6371                  # Earth radius in kilometers
    rm = rkm * 1000             # Radius in meters

    dlat_rad = (loc2[0] - loc1[0]) * rad_per_deg # Delta, converted to rad
    dlon_rad = (loc2[1] - loc1[1]) * rad_per_deg

    lat1_rad, lon1_rad = loc1.map {|i| i * rad_per_deg }
    lat2_rad, lon2_rad = loc2.map {|i| i * rad_per_deg }

    a = Math.sin(dlat_rad/2)**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * Math.sin(dlon_rad/2)**2
    c = 2 * Math::atan2(Math::sqrt(a), Math::sqrt(1-a))

    (rm * c / 1000).round # Delta in km
  end


end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index]

  def index
    if !params[:query].present? || params[:query].empty?
      @restaurants = Restaurant.geocoded
    else
      @restaurants = Restaurant.near(params[:query], 10)
    end

    @markers = @restaurants.geocoded.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { restaurant: restaurant })
        #image_url: helpers.asset_url('images/map.jpg')
      }
    end
  end



  def show
    @restaurant = Restaurant.find(params[:id])
    @dishes = @restaurant.dishes
    @ingredients = @restaurant.ingredients

  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user

    if @restaurant.save
      flash[:success] = "Thanks for adding your restaurant!"
      redirect_to @restaurant
    else
      render :new
      flash[:alert] = "Sorry, your restaurant is not saved!"
    end
  end

  def edit
    unless @restaurant.user == current_user
      redirect_to @restaurant
    end
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to @restaurant, notice: "Restaurant was succesfully updated"
  end

  def destroy
    @restaurant.destroy
    redirect_to my_restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :cuisine, :photo)
  end
end

app/views/restaurants/_info_window.html.erb
<!-- <h3><%= restaurant.name %></h3>
<p><%= restaurant.address %></p> -->

    <div class="card-content">
      <span class="card-title"><h3><%= restaurant.name %></h3></span>
           <p><%= restaurant.address %></p>
           <i class="fas fa-star"></i>
           <i class="fas fa-star"></i>
           <i class="fas fa-star"></i>
           <i class="fas fa-star-half-alt"></i>
    </div>

app/views/restaurants/edit.html.erb
<section>

  <div class="container my-3">
    <div class="special-row justify-content-center">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1 mt-3">
        <h1>Update restaurant details</h1>
        <%= simple_form_for @restaurant do |f| %>
          <%= f.input :name %>
          <%= f.input :address %>
          <%= f.input :phone_number %>
          <%= f.input :cuisine, collection: Restaurant::CUISINES %>
          <%= f.input :photo, as: :file %>
          <%= f.submit class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  <%= link_to "Back to #{@restaurant.name} Restaurant", restaurant_path(@restaurant), class: "btn purple-button mb-3" %>
  </div>
</section>

app/views/restaurants/index.html.erb
<section>


<div class="main-container d-flex justify-content-between">
  <div class="restaurants-wrapper">
    <div class="row">
      <% @restaurants.each do |restaurant| %>
        <div class="col-12 col-md-6 col-sm-12 col-lg-4">


          <div class="card-trip">
            <% if restaurant.photo.attached? %>
              <%= cl_image_tag restaurant.photo.key, height: 300, crop: :fill, class: "card-trip-image" %>
            <% else %>
              <%= image_tag 'https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80', class: "card-trip-image" %>
            <% end %>
            <div class="card-trip-infos">
              <div>
                <%= link_to restaurant_path(restaurant) do %>
                  <h2 style="color: white !important"><%= restaurant.name %></h2>
                <% end %>
                <p><%= restaurant.cuisine %></p>

                </div>
                <p class="card-trip-pricing"><i class="fas fa-map-marker-alt mr-1"></i><%= restaurant.show_distance%> km</p>
                <span class="card-trip-user rating-stars">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star-half-alt"></i>
                </span>

              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

</section>

app/views/restaurants/new.html.erb
<section>

  <div id="special-margin" class="container">
    <div class="special-row justify-content-center">
      <div class="col-12 col-sm-4">
        <h2>Create a new restaurant</h2>
        <%= simple_form_for @restaurant do |f| %>
          <%= f.input :name %>
          <%= f.input :address %>
          <%= f.input :phone_number %>
          <%= f.input :cuisine, collection: Restaurant::CUISINES %>
          <%= f.input :photo, as: :file %>
          <%= f.submit class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>

</section>

app/views/restaurants/show.html.erb
<section>
  <div class="background">

  <div class="container my-3">
    <div class="row justify-content-center">
      <div class="col-12 col-sm-10 col-lg-10">
        <div class="card shadow-sm p-3 mb-5 bg-body rounded align-items-center">
          <h1><%= @restaurant.name %></h1>
          <h5>Address: <%= @restaurant.address %></h5>
          <h5>Phone_number: <%= @restaurant.phone_number %></h5>
          <h5>Cuisine: <%= @restaurant.cuisine %></h5>

          <% if @restaurant.photo.attached? %>
            <%= cl_image_tag @restaurant.photo.key, height: 250, crop: :fill %>
          <% else %>
            <%= image_tag 'https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80', height: 250, crop: :fill %>
          <% end %>

          <% if @restaurant.user == current_user %>
            <div class=" align-items-center mt-3">
              <%= link_to 'Edit Restaurant', edit_restaurant_path(@restaurant), class: "btn btn-secondary" %>
              <%= link_to 'Delete Restaurant', restaurant_path(@restaurant), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-secondary" %>
            </div>
            <%= link_to 'All Ingredients', restaurant_ingredients_path(@restaurant), class: "btn btn-secondary mt-1" %>
          <% end %>
        </div>

        <div class="d-flex justify-content-between">
          <% if @restaurant.user == current_user %>
          <div>
            <%= link_to 'Add Ingredient', new_restaurant_ingredient_path(@restaurant), class: "btn orange-button mb-1" %>
          </div>
          <% end %>
          <% if @restaurant.user == current_user && @restaurant.ingredients.present? %>
            <div class="mb-3">
              <%= link_to 'Add a dish to the menu', new_restaurant_dish_path(@restaurant), class: "btn orange-button" %>
            </div>
          <% end %>
        </div>
        <div class="card shadow-sm p-3 mb-4 bg-body rounded">
          <div class="d-flex justify-content-center">
            <h2 class="m-4 h2">Menu</h2>
          </div>
          <% @dishes.each do |dish| %>
            <div class="card shadow-sm py-3 pl-5 pr-3 my-4 bg-body rounded">
              <div class="d-flex justify-content-between align-items-center mt-1">

                <div>
                  <h4><%= dish.name %></h4>
                </div>

                <div>
                  <% if @restaurant.user != current_user %>
                    <%= link_to "Customize the Dish", order_items_path(@dish, format: "#{dish.id}"), method: :post, class: "btn orange-button" %>
                  <% else %>
                    <%= link_to "Edit the Dish", edit_dish_path(dish), method: :get, class: "btn btn-secondary" %>
                    <%= link_to "Delete the Dish", dish_path(dish), method: :delete, data:{confirm: 'Are you sure?'}, class: "btn btn-secondary" %>
                  <% end %>
                </div>
              </div>

              <ul>
                <% dish.dish_ingredients.each do |dish_ingredient| %>
                  <li><%= dish_ingredient.ingredient.name %></li>
                <% end %>
              </ul>

            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-12 col-sm-10 col-lg-10">
        <%= link_to "Back to all restaurants", restaurants_path, class: "btn purple-button" %>
        <%# if @restaurant.user == current_user %>
          <%#= link_to "My Restaurants", my_restaurants_path, class: "btn btn-secondary" %>
        <%# end %>
      </div>
    </div>
  </div>
  </div>

</section>